### ISSUE TITLE
Bug reported via Discord

### ISSUE THREAD

**Issue by flori4nk** [flori4nk/VelocityAutoReconnect#17]
Possible bug awaiting triage, I'll take a look at this as soon as I have time.

---

Logs (PII removed):
```
[14:25:34] [Netty epoll Worker #0/INFO]: [server connection] **USER** -> backend has connected
[14:25:40] [Velocity Task Scheduler - #243/INFO]: Connecting **USER** to backend.
[14:25:40] [Netty epoll Worker #2/INFO]: [server connection] **USER** -> backend has connected
[14:25:41] [Netty epoll Worker #2/INFO]: [server connection] **USER** -> backend has disconnected
[14:25:41] [Netty epoll Worker #2/ERROR]: Exception during connect; status = null
java.util.concurrent.CompletionException: java.io.IOException: Unexpectedly disconnected from remote server
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:206) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:112) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.IOException: Unexpectedly disconnected from remote server
	at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:205) ~[velo.jar:1.1.9-SNAPSHOT (git-baaf91a0-b444)]
	... 26 more
[14:25:41] [Netty epoll Worker #0/ERROR]: [connected player] **USER** (/): kicked from server backend: multiplayer.disconnect.duplicate_login
[14:25:41] [Netty epoll Worker #0/INFO]: [server connection] **USER** -> backend has disconnected
[14:25:41] [Netty epoll Worker #0/INFO]: [server connection] **USER** -> limbo has connected
[14:25:42] [Velocity Task Scheduler - #243/INFO]: Connecting **USER** to backend.
```

Steps to reproduce:
1. Allow players to join to the backend server. Stop the server. The players will be moved into limbo.
1. Wait for the backend server to boot up, and then stop it again immediately.
1. And, the second time, when the backend boots up, and velocityautoreconnect tries to connect the player back, this error shows up.

----

Thanks to @KoxSosen for reporting the bug.

**Comment by flori4nk** [comment]
Error likely caused by sudden server shutdown, unrelated to VelocityAutoReconnect.
