### ISSUE TITLE
Api issue with the latest velocity snapshot.

### ISSUE THREAD

**Issue by KoxSosen** [flori4nk/VelocityAutoReconnect#4]
I installed the plugin and restarted my proxy. I'm facing this error:
```[08:13:30 ERROR]: Some errors occurred whilst posting event ProxyInitializeEvent.
[08:13:30 ERROR]: #1:

java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:148) ~[?:?]
        at de.flori4nk.velocityautoreconnect.VelocityAutoReconnect.onInitialize(VelocityAutoReconnect.java:120) ~[?:?]
        at net.kyori.event.asm.generated.480116e5b0.VelocityAutoReconnect-onInitialize-ProxyInitializeEvent-13.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velo.jar:1.1.5-SNAPSHOT (git-ca52f898-b408)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velo.jar:1.1.5-SNAPSHOT (git-ca52f898-b408)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:154) ~[velo.jar:1.1.5-SNAPSHOT (git-ca52f898-b408)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:136) ~[velo.jar:1.1.5-SNAPSHOT (git-ca52f898-b408)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]```

**Comment by KoxSosen** [comment]
+ information to the error: Only happens when you first download the jar without the configuration, I'm using the latest velocity snapshot.

**Comment by flori4nk** [comment]
This is expected behaviour when the "default" server cannot be found. However, I'll catch the exception and log an error message instead.

**Comment by flori4nk** [comment]
Fixed

**Comment by KoxSosen** [comment]
Can confirm, fixed on the latest relase.
